name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: 04-using-actions/react-app
        
        steps:
            # 0. Checkout the code from the repository
            - name: Checkout Code
              uses: actions/checkout@v4
            #- name: Printing Folders
            #  run: ls
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '24.x'
            # 1. Install dependencies of our react application
            - name: Install Dependencies
              run: npm ci
              #working-directory: 04-using-actions/react-app
              
            # 2. Execute automated tests
            - name: Run Unit Tests
              run: npm run test
              #working-directory: 04-using-actions/react-app



