name: 08 - Using Variables
on:
    push:
    workflow_dispatch:

env:
   WORKFLOW_VAR: "I am a Workflow var"
   OVERWRITTEN: "I will be overwritten"

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "I am a Job env var"
            OVERWRITTEN: "I have been overwritten at job level"
        steps:
            - name: "Print Env Variables"
              env:
                STEP_VAR: "I am a step env var"
                STEP_VAR2: "I am another step env var"
              run: |
                echo "Step env var: ${{ env.STEP_VAR }}"
                echo "Step env var 2: ${{ env.STEP_VAR2 }}"
                echo "Job env var: ${{ env.JOB_VAR }}"
                echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
                echo "Overwritten: ${{ env.OVERWRITTEN }}"
            - name: "Overwrite Job variable"
              env:
                OVERWRITTEN: "I have been overwritten at the step level"
              run: |
                echo "Overwritten: ${{ env.OVERWRITTEN }}"