name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
              type: boolean
              description: "Whether to execute cache step"
              default: true
            node-version:
              type: choice
              description: "Node.js version to use"
              options:
                - "22.x"
                - "21.x"
                - "23.x"
                - "24.x"
              default: "24.x"
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4
            - name: "Setup Node"
              uses: actions/setup-node@v4
              with:
                node-version: ${{ inputs.node-version }}
            - name: "Install dependencies"
              run: npm ci
            - name: "Testing"
              run: npm run test
            - name: "Building"
              run: npm run build
            - name: "Deploying to nonprod"
              run: echo "Deploying to nonprod"
